const a = 1000;
a=60; //TypeError: Assignment to constant variable.
function f(){
    const b = 500;
    console.log(a);// Unreachable...
    console.log(b);// Unreachable... 
    console.log(c);// Unreachable...
    if(true){
        const c = 3000;
    }
}

f();

console.log(a);// Unreachable...
console.log(b);// Unreachable...
console.log(c);// Unreachable...